print("# FAQs for Recipes for H2O Driverless AI\n")
print("## BYOR TRANSFORMERS\n")
print("  * Introduction\n")
print("  * [Custom Transformer Recipe SDK/API Reference](base_classes/custom_transformer.py)\n")
print("## BYOR MODELS\n")
print("  * Introduction\n")
print("  * [Custom Model Recipe SDK/API Reference](base_classes/custom_model.py)\n")
print("## BYOR SCORERS\n")
print("  * Introduction\n")
print("  * [Custom Scorer Recipe SDK/API Reference](base_classes/custom_scorer.py)\n")
