print("# FAQs for Recipes for H2O Driverless AI\n")
print("* BYOR TRANSFORMERS\n")
print("Custom Transformer Recipes are implemented via the following API:\n")
print('```')
print(open("FAQ.transformers.py", "rt").read())
print('```')
print("* BYOR MODELS\n")
print("Custom Model Recipes are implemented via the following API:\n")
print('```')
print(open("FAQ.models.py", "rt").read())
print('```')
print("* BYOR SCORERS\n")
print("Custom Scorer Recipes are implemented via the following API:\n")
print('```')
print(open("FAQ.scorers.py", "rt").read())
print('```')
